package com.app.weather.service;

import com.app.weather.models.WeatherData;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

@Service
public class WeatherService {
    private final RestTemplate restTemplate = new RestTemplate();

    public WeatherData getWeatherData() {
        String url = "https://api.open-meteo.com/v1/forecast?latitude=45.3143&longitude=26.1509&daily=apparent_temperature_max,apparent_temperature_min,temperature_2m_min,temperature_2m_max,weather_code,uv_index_clear_sky_max,uv_index_max,sunshine_duration,sunset,daylight_duration,sunrise,precipitation_sum,snowfall_sum,showers_sum,rain_sum,precipitation_probability_max,precipitation_hours,shortwave_radiation_sum,wind_direction_10m_dominant,wind_speed_10m_max,wind_gusts_10m_max,et0_fao_evapotranspiration,temperature_2m_mean,apparent_temperature_mean,cape_mean,cape_min,cloud_cover_mean,cape_max,cloud_cover_min,dew_point_2m_mean,cloud_cover_max,dew_point_2m_max,dew_point_2m_min,pressure_msl_min,pressure_msl_max,pressure_msl_mean,snowfall_water_equivalent_sum,relative_humidity_2m_min,relative_humidity_2m_max,precipitation_probability_min,relative_humidity_2m_mean,precipitation_probability_mean,leaf_wetness_probability_mean,growing_degree_days_base_0_limit_50,et0_fao_evapotranspiration_sum,visibility_mean,surface_pressure_min,surface_pressure_mean,surface_pressure_max,updraft_max,visibility_min,visibility_max,wind_speed_10m_mean,wind_speed_10m_min,wind_gusts_10m_min,winddirection_10m_dominant,wind_gusts_10m_mean,vapour_pressure_deficit_max,wet_bulb_temperature_2m_min,wet_bulb_temperature_2m_max,wet_bulb_temperature_2m_mean&hourly=temperature_2m,wind_speed_10m,rain,showers,snow_depth,snowfall,precipitation,precipitation_probability,apparent_temperature,weather_code,visibility,cloud_cover_mid,cloud_cover_low,surface_pressure,pressure_msl,cloud_cover,cloud_cover_high,dew_point_2m,relative_humidity_2m,evapotranspiration,et0_fao_evapotranspiration,vapour_pressure_deficit,temperature_80m,temperature_180m,temperature_120m,wind_gusts_10m,wind_direction_180m,wind_direction_120m,wind_direction_80m,wind_direction_10m,wind_speed_180m,wind_speed_120m,soil_temperature_6cm,soil_temperature_0cm,soil_temperature_54cm,soil_temperature_18cm,wind_speed_80m,soil_moisture_1_to_3cm,soil_moisture_3_to_9cm,soil_moisture_0_to_1cm,soil_moisture_9_to_27cm,soil_moisture_27_to_81cm&current=relative_humidity_2m,is_day,apparent_temperature,temperature_2m,precipitation,rain,showers,snowfall,pressure_msl,cloud_cover,weather_code,surface_pressure,wind_gusts_10m,wind_speed_10m,wind_direction_10m&forecast_days=1";

        return restTemplate.getForObject(url, WeatherData.class);
    }
}